export const categories = [
  {
    id: 1,
    name: "Audio",
    image: "/quest-3.png",
  },
  {
    id: 2,
    name: "Smartphones",
    image: "/ps-portal-1.png",
  },
  {
    id: 3,
    name: "Laptops",
    image: "/ps-portal-2.png",
  },
  {
    id: 4,
    name: "Gaming",
    image: "/quest-3.png",
  },
  {
    id: 5,
    name: "Accessories",
    image: "/quest-3.png",
  },
];
export const bestSellers = [
  {
    id: 1,
    name: "iPhone 13 Pro",
    brand: "Apple",
    price: 950000,
    image: "/quest-3.png",
  },
  {
    id: 2,
    name: "Samsung Galaxy S22",
    brand: "Samsung",
    price: 780000,
    image: "/ps-portal-2.png",
  },
  {
    id: 3,
    name: "MacBook Air M2",
    brand: "Apple",
    price: 1200000,
    image: "/quest-3.png",
  },
  {
    id: 4,
    name: "HP Pavilion 15",
    brand: "HP",
    price: 650000,
    image: "/quest-3.png",
  },
  {
    id: 5,
    name: "Wireless Earbuds",
    brand: "Generic",
    price: 25000,
    image: "/quest-3.png",
  },
  {
    id: 6,
    name: "Noise Cancelling Headphones",
    brand: "Sony",
    price: 85000,
    image: "/quest-3.png",
  },
  {
    id: 7,
    name: "PlayStation 5",
    brand: "Sony",
    price: 950000,
    image: "/quest-3.png",
  },
  {
    id: 8,
    name: "Gaming Keyboard",
    brand: "Logitech",
    price: 120000,
    image: "/quest-3.png",
  },
  {
    id: 9,
    name: "Fast Charger 65W",
    brand: "Anker",
    price: 18000,
    image: "/quest-3.png",
  },
  {
    id: 10,
    name: "USB-C Hub Adapter",
    brand: "Ugreen",
    price: 35000,
    image: "/quest-3.png",
  },
];
export const featuredProducts = [
  {
    id: 1,
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    price: 1150000,
    image: "/alienware-backview-1.png",
  },
  {
    id: 2,
    name: "Samsung Galaxy Z Fold",
    brand: "Samsung",
    price: 1350000,
    image: "/alienware-headset.png",
  },
  {
    id: 3,
    name: "MacBook Pro M2",
    brand: "Apple",
    price: 1850000,
    image: "/asus-gaming-laptop-1.png",
  },
  {
    id: 4,
    name: "Dell XPS 13",
    brand: "Dell",
    price: 1250000,
    image: "/fifa-26.png",
  },
  {
    id: 5,
    name: "Sony WH-1000XM5",
    brand: "Sony",
    price: 180000,
    image: "/gaming-monitor-curve.png",
  },
  {
    id: 6,
    name: "Apple Watch Series 8",
    brand: "Apple",
    price: 420000,
    image: "/quest-3.png",
  },
  {
    id: 7,
    name: "iPad Pro",
    brand: "Apple",
    price: 980000,
    image: "/switch.png",
  },
  {
    id: 8,
    name: "Gaming Monitor 144Hz",
    brand: "LG",
    price: 320000,
    image: "/x-box.png",
  },
];
